#!/bin/bash
set -euo pipefail

if [ $# -ne 4 ]; then
  echo >&2 "usage: $0 yourname egglinuxdir builddir outputdir"
  echo >&2 "e.g., after './hatch x': $0 $(id -un) . x /tmp/egg-build-report"
  exit 2
fi
reporter=$1
eggLinuxDir=$2
buildDir=$3
out=$4

mkdir -p "$out"/build-machine
echo "$reporter" >"$out"/reporter
date -uI >"$out"/date
sha256sum "$buildDir"/checksums/sha256sums |cut -c-64 \
  >"$out"/result-checksum
git --work-tree "$eggLinuxDir" rev-parse HEAD >"$out"/egg-linux-commit
gcc --version |head -n1 >"$out"/build-machine/gcc-version
lsb_release -d |sed 's/.*:\s*//' >"$out"/build-machine/lsb-release
uname -a >"$out"/build-machine/uname
libc=$(ldd /bin/true |sed 's,=>, ,' |awk '$1 ~ /^libc.so/ { print $2 }')
"$libc" --version |head -n1 >"$out"/build-machine/libc-version

set +e
curl_err=$(curl -sS --connect-timeout 2 http://169.254.169.254/latest/meta-data 2>&1 >/dev/null)
curl_ret=$?
set -e
case "$curl_ret" in
  0)
    curl -sS http://169.254.169.254/latest/meta-data/ami-id \
      >"$out"/build-machine/ec2-ami-id
    curl -sS http://169.254.169.254/latest/meta-data/instance-type \
      >"$out"/build-machine/ec2-instance-type
    ;;
  28)  # timed out; just means it's not an EC2 instance, probably
    ;;
  *)
    echo >&2 "$curl_err"
    echo >&2 "$0: error: curl exited with code $curl_ret"
    exit 1
esac
