#!/bin/bash
set -euo pipefail
here=$(dirname "${BASH_SOURCE[0]}")
here=$(readlink -f "$here")

if [ $# -lt 2 ]; then
  echo >&2 "usage: $0 outputdir buildscript [input ...]"
  exit 1
fi
out=$(readlink -f "$1")
shift
script_name=$(basename "$1")
script=$(readlink -f "$1")
shift
inputs=("$@")

if [ -e "$out"/.built ]; then
  shouldBuild=no
  if [ "$script" -nt "$out"/.built ]; then
    echo >&2 "$0: should build: $script is newer than $out"
    shouldBuild=yes
  elif [ -v inputs ]; then
    for i in "${inputs[@]}"; do
      if [ "$i"/.built -nt "$out"/.built ]; then
        echo >&2 "$0: should build: $i is newer than $out"
        shouldBuild=yes
        break
      fi
    done
  fi
else
  echo >&2 "$0: should build: $out has not been built"
  shouldBuild=yes
fi

cleanup() {
  if [ -v LEAVE_WORKING_DIR ]; then
    echo >&2 "$1"
  else
    find "$1" -type d -execdir chmod u+w {} +
    rm -rf "$1"
  fi
}

case "$shouldBuild" in
  yes)
    echo >&2 "$0: building: $out"
    unset workdir
    trap 'if [ -v workdir ]; then cleanup "$workdir"; fi' EXIT
    workdir=$(mktemp -d --tmpdir "$script_name".XXXXXXXX)
    if [ -d "$out" ]; then
      find "$out" -type d -execdir chmod u+w {} +
    fi
    rm -rf "$out"
    (
      inputsvars=()
      if [ -v inputs ]; then
        inputspaths=()
        for i in "${inputs[@]}"; do
          name=$(basename "$i")
          fullpath=$(readlink -f "$i")
          inputspaths+=("$fullpath")
          inputsvars+=("${name//-/_}=$fullpath")
        done
        IFS=:
        if [ -v PASS_PATH_THROUGH ] && [ -v inputspaths ]; then
          path=$PATH:"${inputspaths[*]/%//bin}"
        elif [ -v PASS_PATH_THROUGH ]; then
          path=$PATH
        elif [ -v inputspaths ]; then
          path="${inputspaths[*]/%//bin}"
        else
          path=
        fi
        inputsvars+=(
          CPATH="${inputspaths[*]/%//include}"
          LD_LIBRARY_PATH="${inputspaths[*]/%//lib}"
          LIBRARY_PATH="${inputspaths[*]/%//lib}"
          PATH="$path"
        )
        unset IFS
      fi
      workdirEscaped=$(sed -e 's,%,%#,g' -e 's,=,%+,g' -e 's,:,%.,g' <<< "$workdir")
      cd "$workdir"
      env -i \
        out="$out" \
        src="$here"/src \
        SOURCE_DATE_EPOCH=1 \
        BUILD_PATH_PREFIX_MAP="$workdirEscaped"= \
        ${inputsvars:+"${inputsvars[@]}"} \
        /bin/bash -euo pipefail -- "$script"
    )
    find "$out" ! -type l -execdir chmod u+w {} +
    find "$out" -type f -execdir strip -d {} + || true
    touch "$out"/.built
    find "$out" ! -type l -execdir chmod a-w {} +
    ;;
  no)
    echo >&2 "$0: not building: $out"
    exit 0
    ;;
  *)
    echo >&2 "$0: internal error: $shouldBuild"
    exit 2
    ;;
esac
