#!/bin/bash
set -euo pipefail
here=$(dirname "${BASH_SOURCE[0]}")

if [ $# -ne 1 ]; then
  echo >&2 "usage: $0 outputdir"
  exit 1
fi
out=$1

build() {
  module=$1
  shift
  "$here"/build "$out/$module" "$here/module/$module" "${@/#/$out/}"
}

mkdir -p "$out"
build gperf
build which
build ctng gperf which
build cross ctng
build cross-native cross ctng
build static-bash cross
build coreutils cross
build tar cross
build gzip cross
build bzip2 cross
build xz cross
build grep cross
build awk cross
build sed cross
build diffutils cross
build patch cross
build findutils cross
build linux cross
build xorriso
build grub xorriso
build tree linux static-bash cross-native \
  coreutils tar gzip bzip2 xz \
  grep awk sed \
  diffutils patch findutils
build image grub xorriso tree
