#!/bin/bash
set -euo pipefail
here=$(dirname "${BASH_SOURCE[0]}")

if [ $# -ne 1 ]; then
  echo >&2 "usage: $0 outputdir"
  exit 1
fi
out=$1

stdenv=()

stdtool() {
  stdenv+=("$out/$1")
}

package() {
  local pkg start finish
  pkg=$1
  shift
  start=$(date -u +%s)
  "$here"/build "$out/$pkg" "$here/package/$pkg" \
    ${stdenv:+"${stdenv[@]}"} ${@:+"${@/#/$out/}"}
  finish=$(date -u +%s)
  echo "$((finish - start)) $pkg" >> "$out"/times
}

mkdir -p "$out"
date -Is >> "$out"/times
. "$here"/packages
